typography_spectrum: 0.6181269127409905
color:
  brandColors:
    - '#ffffff'
    - '#d77438'
    - '#212122'
    - '#626262'
    - '#bebebe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7482
analytics:
  google: UA-76140371-1
  facebook: '901001630029147'
  twitter: null
author:
  name: Fabian Hernandez
  email: contact@cocoknight.com
  url: 'http://cocoknight.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/748d06f0-48fd-43ef-be4e-c9881d907a7a.svg
name: coCoKNIght
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/998254e3-75c9-4dbc-8adb-8d6e8d390cd5.ico
title: coCoKNIght.com
description: Online Portfolio of Fabian Hernandez
purpose: []
