name: coCoKNIght
favicon: null
layout_spectrum: 0.7482
typography_spectrum: 0.78283
title: coCoKNIght.com - Online Portfolio of Fabian Hernandez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76140371-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3ebe8'
    - '#c8c5c3'
    - '#ff7036'
    - '#938f8d'
    - '#d6978d'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
