name: coCoKNIght
favicon: null
layout_spectrum: 0.7482
typography_spectrum: 0.78283
title: coCoKNIght.com - Online Portfolio of Fabian Hernandez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76140371-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d77438'
    - '#212122'
    - '#626262'
    - '#bebebe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
