name: coCoKNIght
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/998254e3-75c9-4dbc-8adb-8d6e8d390cd5.ico
layout_spectrum: 0.7482
typography_spectrum: 0.78283
author:
  name: Fabian Hernandez
  email: contact@cocoknight.com
  url: 'http://cocoknight.com'
title: coCoKNIght.com - Online Portfolio of Fabian Hernandez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76140371-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d77438'
    - '#212122'
    - '#626262'
    - '#bebebe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
