name: coCoKNIght
favicon: null
layout_spectrum: 0.7482
typography_spectrum: 0.78283
title: coCoKNIght.com - Online Portfolio of Fabian Hernandez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76140371-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#808334'
    - '#0a495d'
    - '#c0c351'
    - '#0ea2bb'
    - '#f7f6e7'
  brandStrength: 0.625
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
