name: coCoKNIght
favicon: null
layout_spectrum: 0.4374482159037143
typography_spectrum: 0.145338294794783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3248257553204894
  lightness: 0.43356667924672365
  saturation: 0.2344422754831612
  rhythmicContrast: 0.0009947794023901224
purpose: []
