name: coCoKNIght
favicon: null
layout_spectrum: 0.7482
typography_spectrum: 0.78283
title: coCoKNIght.com - Online Portfolio of Fabian Hernandez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76140371-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#acc8b2'
    - '#291419'
    - '#847069'
    - '#eca549'
  brandStrength: 0.625
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
